

import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font"; // Updated import
import "./globals.css";

export const metadata: Metadata = {
  title: "Ofosuhene's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}